In [3]:
import numpy as np

# Ймовірність того, що деталь буде стандартною
p_standard = 0.6

# Кількість перевірених деталей
n = 3

# Кількість бракованих деталей
X_values = np.arange(0, n + 1)

# Кількість стандартних деталей
Y_values = np.arange(n, -1, -1)

# Ймовірності появи числа бракованих і стандартних деталей
p_X = np.array([(1 - p_standard) ** (n - k) * p_standard ** k for k in X_values])
p_Y = np.array([(1 - p_standard) ** k * p_standard ** (n - k) for k in Y_values])

# Закон розподілу системи двох дискретних випадкових величин X і Y
joint_probabilities = np.outer(p_X, p_Y)

# Обчислення коефіцієнта кореляції r_xy
E_X = np.sum(X_values * p_X)
E_Y = np.sum(Y_values * p_Y)
Cov_XY = np.sum(np.outer(X_values - E_X, Y_values - E_Y) * joint_probabilities)
Var_X = np.sum((X_values - E_X) ** 2 * p_X)
Var_Y = np.sum((Y_values - E_Y) ** 2 * p_Y)
r_xy = Cov_XY / np.sqrt(Var_X * Var_Y)

# Виведення результатів
print("Закон розподілу дискретних випадкових величин X і Y:")
print(joint_probabilities)
print("Коефіцієнт кореляції r_xy:", r_xy)


Закон розподілу дискретних випадкових величин X і Y:
[[0.004096 0.006144 0.009216 0.013824]
 [0.006144 0.009216 0.013824 0.020736]
 [0.009216 0.013824 0.020736 0.031104]
 [0.013824 0.020736 0.031104 0.046656]]
Коефіцієнт кореляції r_xy: 0.14806895757046815


In [1]:
import numpy as np

# Дані з умов задачі
X = np.array([
    [10, 0.01, 0.03, 0.02, 0.03, 0.01],
    [5, 0.03, 0.09, 0.06, 0.09, 0.03],
    [2, 0.02, 0.06, 0.04, 0.06, 0.02],
    [1, 0.03, 0.09, 0.06, 0.09, 0.03],
    [-5, 0.01, 0.03, 0.02, 0.03, 0.01]
])

Y = np.array([20, 10, 2, -2, -8])
P_X = np.array([0.1, 0.3, 0.2, 0.3, 0.1])
P_Y = np.array([0.1, 0.3, 0.2, 0.3, 0.1])

# Задача 2.1 Обчислення очікуваної норми прибутку
expected_profit_X = np.dot(X[:, 0], P_X)
expected_profit_Y = np.dot(Y, P_Y)

print("Очікувана норма прибутку для акції X:", expected_profit_X)
print("Очікувана норма прибутку для акції Y:", expected_profit_Y)

# Задача 2.2 Обчислення середньоквадратичного відхилення
std_dev_X = np.sqrt(np.dot((X[:, 0] - expected_profit_X) ** 2, P_X))
std_dev_Y = np.sqrt(np.dot((Y - expected_profit_Y) ** 2, P_Y))

print("Середньоквадратичне відхилення для акції X:", std_dev_X)
print("Середньоквадратичне відхилення для акції Y:", std_dev_Y)

# Задача 2.3 Обчислення коваріації та кореляції
covariance = np.dot(np.dot(X[:, 0] - expected_profit_X, Y - expected_profit_Y), P_X * P_Y)
correlation = covariance / (std_dev_X * std_dev_Y)

print("Коваріація між акціями X та Y:", covariance)
print("Кореляція між акціями X та Y:", correlation)


Очікувана норма прибутку для акції X: 2.7
Очікувана норма прибутку для акції Y: 4.0
Середньоквадратичне відхилення для акції X: 3.7161808352124095
Середньоквадратичне відхилення для акції Y: 7.899367063252599
Коваріація між акціями X та Y: [ 2.346 21.114  9.384 21.114  2.346]
Кореляція між акціями X та Y: [0.07991694 0.7192525  0.31966778 0.7192525  0.07991694]


In [ ]:
# Ну chatgpt сильнор допоміг, помилок було багато, здається все правильно тепер